version: '3.8' 

services:
  # FastAPI API 服務
  api:
    image: danielhch/product_service:latest
    container_name: api_container # 容器名稱
    ports:
      # 將主機的 8000 端口映射到容器的 8000 端口 (與 Dockerfile 暴露的 port 要一樣)
      - "8000:8000"
    environment:
      - MYSQL_USER=root # 上面服務名稱叫什麼這邊就一樣的
      - MYSQL_PASSWORD=test
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=product

    depends_on:
      # 確保 mysql 服務先於 API
      - mysql
    networks:
      # 指定使用的網路
      - app_network
  mysql:
  # mysql 服務
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=product
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql 

    networks:
      # 指定使用的網路
      - app_network
  

networks:
  app_network:
    driver: bridge # 使用預設的

volumes:
  mysql_data: